### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/chombo/util/SecondarySort$TuplePairGroupComprator

### ISSUE THREAD

**Issue by balureddy** [pranab/sifarish#8]
Hi Pranab,

Please find the above exception while running implicit rating genaeration script. Please let me know how to resolve the issue.

Exception in thread "main" java.lang.NoClassDefFoundError: org/chombo/util/SecondarySort$TuplePairGroupComprator
	at org.sifarish.common.ImplicitRatingEstimator.run(ImplicitRatingEstimator.java:73)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.sifarish.common.ImplicitRatingEstimator.main(ImplicitRatingEstimator.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: java.lang.ClassNotFoundException: org.chombo.util.SecondarySort$TuplePairGroupComprator

**Comment by pranab** [comment]
Have you gone through ..resource/tutorial.txt . It refers to  ../resource/jar_dependency.txt which documents  how to resolve run time dependencies. You don't have chombo jar in your class path

Pranab

http://www.linkedin.com/in/pkghosh 
http://pkghosh.wordpress.com
 



Date: Wed, 8 Apr 2015 22:15:26 -0700
