### ISSUE TITLE
Found interface org.apache.hadoop.mapreduce.Counter, but class was expected

### ISSUE THREAD

**Issue by bhoomit** [pranab/sifarish#9]
Stack trace:
```
java.lang.Exception: java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
	at org.sifarish.feature.SameTypeSimilarity$SimilarityReducer.reduce(SameTypeSimilarity.java:361)
	at org.sifarish.feature.SameTypeSimilarity$SimilarityReducer.reduce(SameTypeSimilarity.java:237)
	at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```
This is the error that I got when I execute org.sifarish.feature.SameTypeSimilarity

I tried this http://stackoverflow.com/questions/18967147/cdh4-version-conflict-found-interface-org-apache-hadoop-mapreduce-counter-but but it didn't work. I'm pretty new to mvn and Java world. Am I doing something wrong here?

**Comment by pranab** [comment]
Seems Luke you are using hadoop2. Read the instructions in project home page and document In resource directory in how to checkout the branch nuovo and build for hadoop2 or hadoop2/yarn
Pranab

**Comment by bhoomit** [comment]
Got it. Thanks :)
